name: Daily Weather Scripts and Upload (Self-Made)

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  run-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Weather_data.py
      run: python Weather_data.py
    
    - name: Install gdrive
      run: |
        curl -L https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive-linux-x64-2.1.1 -o gdrive
        chmod +x gdrive
        sudo mv gdrive /usr/local/bin/

    - name: Verify gdrive installation
      run: |
        which gdrive
        gdrive version

    - name: Authenticate gdrive
      run: |
        echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" > service_account.json
        gdrive about    # เช็คว่าเชื่อมต่อได้
      env:
        GOOGLE_APPLICATION_CREDENTIALS: service_account.json

    - name: Upload file to Google Drive
      run: |
        gdrive upload --parent 1oG1TA6wzl4J45lyCieeoPCj8SDEqgnYC public/output.csv
