name: Update Ourworld to Google Drive
on:
  schedule:
    - cron: '0 0 1 12 *'  
  workflow_dispatch:  

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run OurWorldData scraper
        run: python OurWorldData.py

      - name: Find all generated CSV filenames
        id: find_files
        run: |
          FILES=$(ls *_ourworld_*.csv | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$FILES" >> $GITHUB_OUTPUT

  upload-files:
    needs: update-data
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.update-data.outputs.files) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload ${{ matrix.file }} to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          file: ${{ matrix.file }}
          name: ${{ matrix.file }}
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false
