name: Upload Weather CSV to Google Drive

on:
  schedule:
    - cron: '0 0 * * *'  # รันทุกวันตอนเที่ยงคืน UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout รหัสจาก repository
      - name: Checkout code
        uses: actions/checkout@v3

      # ตั้งค่า Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # ติดตั้ง dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      # รันสคริปต์ Python เพื่อสร้างไฟล์ CSV
      - name: Run weather scraper
        run: python weather_script.py

      # ตรวจสอบว่าไฟล์ CSV ถูกสร้าง
      - name: Check CSV file
        run: ls -la output/

     # อัปโหลดไฟล์ CSV ไป Google Drive
      - name: Upload to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: output/weatherdata.csv
          name: weatherdata.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.DRIVE_CREDENTIALS }}
          encoded: false  # ใช้ JSON ดิบ ไม่ต้องถอดรหัส base64
