name: Update Weather Data to Google Drive

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown

      - name: Download file from Google Drive
        run: |
          gdown https://drive.google.com/drive/folders/${{ secrets.FOLDER_ID }}

      - name: Run weather data scraper
        run: python Weather_data.py

      - name: Upload to Google Drive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: ./weatherdata.csv
          name: weatherdata.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false
