name: Update ourworld to Google Drive
on:
  schedule:
    - cron: '0 0 1 * *'   # 1 ทุกเดือน
  workflow_dispatch:  

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run OurWorldData scraper
        run: python OurWorldData.py

      - name: Upload CO2_ourworld_1.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          file: ./CO2_ourworld_1.csv
          name: CO2_ourworld_1.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false

      - name: Upload CO2_ourworld_2.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          file: ./CO2_ourworld_2.csv
          name: CO2_ourworld_2.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false

      - name: Upload CH4_ourworld_1.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          file: ./CH4_ourworld_1.csv
          name: CH4_ourworld_1.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false

      - name: Upload CH4_ourworld_2.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          file: ./CH4_ourworld_2.csv
          name: CH4_ourworld_2.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false

      - name: Upload N2O_ourworld_1.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          file: ./N2O_ourworld_1.csv
          name: N2O_ourworld_1.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false

      - name: Upload N2O_ourworld_2.csv
        uses: mathisve/gdrive-upload-action@main
        with:
          file: ./N2O_ourworld_2.csv
          name: N2O_ourworld_2.csv
          folderId: ${{ secrets.FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
          encoded: false
