name: Upload CSV to Google Drive

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

    - name: Upload CSV to Google Drive
      env:
        GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
      run: |
        import json
        from google.oauth2 import service_account
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload

        # Load service account info from environment variable
        service_account_info = json.loads('${{ secrets.GDRIVE_SERVICE_ACCOUNT }}')
        credentials = service_account.Credentials.from_service_account_info(
            service_account_info,
            scopes=['https://www.googleapis.com/auth/drive.file']
        )

        drive_service = build('drive', 'v3', credentials=credentials)

        file_metadata = {'name': 'weatherdata.csv'}
        media = MediaFileUpload('path/to/your/file.csv', mimetype='text/csv')

        file = drive_service.files().create(
            body=file_metadata,
            media_body=media,
            fields='id'
        ).execute()

        print(f"Uploaded File ID: {file.get('id')}")
